export const ALL_COURSE_REQUEST = 'ALL_COURSE_REQUEST'
export const ALL_COURSE_SUCCESS = 'ALL_COURSE_SUCCESS'
export const ALL_COURSE_FAIL = 'ALL_COURSE_FAIL'

export const SINGLE_COURSE_DETAILS_REQUEST = 'SINGLE_COURSE_DETAILS_REQUEST'
export const SINGLE_COURSE_DETAILS_SUCCESS = 'SINGLE_COURSE_DETAILS_SUCCESS'
export const SINGLE_COURSE_DETAILS_FAIL = 'SINGLE_COURSE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'