// create all class request constant 
export const GET_ALL_STUDENT_CLASS_REQUEST = 'GET_ALL_STUDENT_CLASS_REQUEST';
export const GET_ALL_STUDENT_CLASS_REQUEST_FAIL = 'GET_ALL_STUDENT_CLASS_REQUEST_FAIL';
export const GET_SINGLE_STUDENT_CLASS_REQUEST = 'GET_SINGLE_STUDENT_CLASS_REQUEST';
export const GET_SINGLE_STUDENT_CLASS_REQUEST_FAIL = 'GET_SINGLE_STUDENT_CLASS_REQUEST_FAIL';

export const CREATE_STUDENT_CLASS_REQUEST = 'CREATE_STUDENT_CLASS_REQUEST';
export const CREATE_STUDENT_CLASS_REQUEST_FAIL = 'CREATE_STUDENT_CLASS_REQUEST_FAIL';

export const UPDATE_STUDENT_CLASS_REQUEST = 'UPDATE_STUDENT_CLASS_REQUEST';
export const UPDATE_STUDENT_CLASS_REQUEST_FAIL = 'UPDATE_STUDENT_CLASS_REQUEST_FAIL';

export const DELETE_STUDENT_CLASS_REQUEST = 'DELETE_STUDENT_CLASS_REQUEST';
export const DELETE_STUDENT_CLASS_REQUEST_FAIL = 'DELETE_STUDENT_CLASS_REQUEST_FAIL';

export const STUDENT_CLASS_REQUEST_ERROR = 'STUDENT_CLASS_REQUEST_ERROR';
