
// create student constants
export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_FAIL = "CREATE_STUDENT_FAIL";

// get all students constants
export const GET_ALL_STUDENTS_REQUEST = "GET_ALL_STUDENTS_REQUEST";
export const GET_ALL_STUDENTS_SUCCESS = "GET_ALL_STUDENTS_SUCCESS";
export const GET_ALL_STUDENTS_FAIL = "GET_ALL_STUDENTS_FAIL";

// get single student constants
export const GET_SINGLE_STUDENT_REQUEST = "GET_SINGLE_STUDENT_REQUEST";
export const GET_SINGLE_STUDENT_SUCCESS = "GET_SINGLE_STUDENT_SUCCESS";
export const GET_SINGLE_STUDENT_FAIL = "GET_SINGLE_STUDENT_FAIL";

// update student profile constants
export const UPDATE_STUDENT_PROFILE_REQUEST = "UPDATE_STUDENT_PROFILE_REQUEST";
export const UPDATE_STUDENT_PROFILE_SUCCESS = "UPDATE_STUDENT_PROFILE_SUCCESS";
export const UPDATE_STUDENT_PROFILE_FAIL = "UPDATE_STUDENT_PROFILE_FAIL";

// delete student constants
export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL";

// add to favorite teacher constants
export const ADD_TO_FAVORITE_TEACHER_REQUEST = "ADD_TO_FAVORITE_TEACHER_REQUEST";
export const ADD_TO_FAVORITE_TEACHER_SUCCESS = "ADD_TO_FAVORITE_TEACHER_SUCCESS";
export const ADD_TO_FAVORITE_TEACHER_FAIL = "ADD_TO_FAVORITE_TEACHER_FAIL";


// remove from favorite teacher constants
export const REMOVE_FROM_FAVORITE_TEACHER_REQUEST = "REMOVE_FROM_FAVORITE_TEACHER_REQUEST";
export const REMOVE_FROM_FAVORITE_TEACHER_SUCCESS = "REMOVE_FROM_FAVORITE_TEACHER_SUCCESS";
export const REMOVE_FROM_FAVORITE_TEACHER_FAIL = "REMOVE_FROM_FAVORITE_TEACHER_FAIL";

// add to favorite course constants
export const ADD_TO_FAVORITE_COURSE_REQUEST = "ADD_TO_FAVORITE_COURSE_REQUEST";
export const ADD_TO_FAVORITE_COURSE_SUCCESS = "ADD_TO_FAVORITE_COURSE_SUCCESS";
export const ADD_TO_FAVORITE_COURSE_FAIL = "ADD_TO_FAVORITE_COURSE_FAIL";

// remove from favorite course constants
export const REMOVE_FROM_FAVORITE_COURSE_REQUEST = "REMOVE_FROM_FAVORITE_COURSE_REQUEST";
export const REMOVE_FROM_FAVORITE_COURSE_SUCCESS = "REMOVE_FROM_FAVORITE_COURSE_SUCCESS";
export const REMOVE_FROM_FAVORITE_COURSE_FAIL = "REMOVE_FROM_FAVORITE_COURSE_FAIL";

