// teachers constants 
export const GET_ALL_TEACHERS = 'GET_ALL_TEACHERS';
export const GET_ALL_TEACHERS_FAIL = 'GET_ALL_TEACHERS_FAIL';
export const GET_SINGLE_TEACHER = 'GET_SINGLE_TEACHER';

export const CREATE_TEACHER = 'CREATE_TEACHER';
export const CREATE_TEACHER_FAIL = 'CREATE_TEACHER_FAIL';

export const UPDATE_TEACHER = 'UPDATE_TEACHER';
export const UPDATE_TEACHER_FAIL = 'UPDATE_TEACHER_FAIL';

export const DELETE_TEACHER = 'DELETE_TEACHER';
export const DELETE_TEACHER_FAIL = 'DELETE_TEACHER_FAIL';

export const TEACHER_ERROR = 'TEACHER_ERROR';

